version: "3.8"

services:
  packager-x64-windows:
    image: packager
    command: sh -c "npm run rebuild:x64 && npm run make:x64-windows"
    volumes:
      - ./package.json:/project/package.json
      - ./forge.config.js:/project/forge.config.js
      - ./out:/project/out
      - ./.env:/project/.env
      - ./build:/project/build

  packager-arm64-windows:
    image: packager
    command: sh -c "npm run rebuild:arm64 && npm run make:arm64-windows"
    volumes:
      - ./package.json:/project/package.json
      - ./forge.config.js:/project/forge.config.js
      - ./out:/project/out
      - ./.env:/project/.env
      - ./build:/project/build

  packager-x64-linux:
    image: packager
    command: sh -c "npm run rebuild:x64 && npm run make:x64-linux"
    volumes:
      - ./package.json:/project/package.json
      - ./forge.config.js:/project/forge.config.js
      - ./out:/project/out
      - ./.env:/project/.env
      - ./build:/project/build

  packager-arm64-linux:
    image: packager
    command: sh -c "npm run rebuild:arm64 && npm run make:arm64-linux"
    volumes:
      - ./package.json:/project/package.json
      - ./forge.config.js:/project/forge.config.js
      - ./out:/project/out
      - ./.env:/project/.env
      - ./build:/project/build

  e2e:
    environment:
      SHORT_BREAK_DURATION_SECONDS: ${SHORT_BREAK_DURATION_SECONDS}
      LONG_BREAK_DURATION_SECONDS: ${LONG_BREAK_DURATION_SECONDS}
      WORK_DURATION_SECONDS: ${WORK_DURATION_SECONDS}
      LONG_BREAK_INTERVAL: ${LONG_BREAK_INTERVAL}
      AUTO_RUN_WORK: ${AUTO_RUN_WORK}
      AUTO_RUN_BREAK: ${AUTO_RUN_BREAK}
      TRELLO_API_KEY: ${TRELLO_API_KEY}
      TRELLO_REDIRECT_URL: ${TRELLO_REDIRECT_URL}
    build:
      dockerfile: ./docker/e2e/Dockerfile
      context: .
    command: >
      sh -c "npm run test:e2e --forceExit"
    volumes:
    - ./e2e:/app/e2e
    - ./.env:/app/.env
    - ./build:/app/build
    - ./jest.config.e2e.js:/app/jest.config.e2e.js
