name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Build & Release
    runs-on: macos-latest

    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^((?!skip ci).)*$'
          flags: 's'
          error: 'Skipping for release commit.'

      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Configure CI Git User
        run: |
          git config --global user.name 'TheUnderScorer'
          git config --global user.email 'przemyslawzydek@gmail.com'
          git remote set-url origin https://TheUnderScorer:$GITHUB_TOKEN@github.com/TheUnderScorer/pixel-pomodo
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install npm dependencies
        run: |
          npm install

      - name: Build main & renderer
        run: |
          npm run build:all

      - name: Build & Release
        run: |
          npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
