name: Tests
on:
  pull_request:
    branches:
      - '*'

jobs:
  units:
    name: Unit tests & linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js 14.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Install npm dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "TRELLO_API_KEY=${{ secrets.TRELLO_API_KEY }}" >> .env
          echo "TRELLO_REDIRECT_URL=${{ secrets.TRELLO_REDIRECT_URL }}" >> .env

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
        env:
          SHORT_BREAK_DURATION_SECONDS: 5
          LONG_BREAK_DURATION_SECONDS: 15
          WORK_DURATION_SECONDS: 10
          LONG_BREAK_INTERVAL: 4
          AUTO_RUN_WORK: false
          AUTO_RUN_BREAK: false

  e2e:
    name: E2E tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js 14.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Install npm dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "TRELLO_API_KEY=${{ secrets.TRELLO_API_KEY }}" >> .env
          echo "TRELLO_TOKEN=${{ secrets.TRELLO_TOKEN }}" >> .env
          echo "TRELLO_REDIRECT_URL=${{ secrets.TRELLO_REDIRECT_URL }}" >> .env

      - name: Build
        run: npm run build:all

      - name: E2E
        run: npm run test:e2e-docker
        env:
          SHORT_BREAK_DURATION_SECONDS: 5
          LONG_BREAK_DURATION_SECONDS: 15
          WORK_DURATION_SECONDS: 10
          LONG_BREAK_INTERVAL: 4
          AUTO_RUN_WORK: false
          AUTO_RUN_BREAK: false


